import { Complaint, IssueCluster, Hotspot, NotificationItem, User } from '../src/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-citizen-1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@example.com',
    phone: '+91 98201 44521',
    role: 'CITIZEN',
    preferredLanguage: 'en',
    savedLocation: {
      address: 'Flat 402, Sai Heritage, ABC College Road',
      landmark: 'Near ABC Engineering College Gate 2',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411007',
      latitude: 18.5314,
      longitude: 73.8446,
    },
  },
  {
    id: 'user-officer-1',
    name: 'Shri Rajesh Kulkarni',
    email: 'rajesh.kulkarni@pcmc.gov.in',
    phone: '+91 94220 18290',
    role: 'AUTHORITY',
    department: 'PWD / Municipal Roads',
    preferredLanguage: 'en',
    badge: 'Executive Engineer - Ward 4',
  },
];

export const INITIAL_CLUSTERS: IssueCluster[] = [
  {
    id: 'CLUSTER-PUNE-001',
    title: 'ABC College Road Severe Potholes & Road Cratering',
    category: 'Roads & Infrastructure',
    department: 'PWD / Municipal Roads',
    location: {
      address: 'ABC College Road, Sector 3, Near College Main Gate',
      landmark: 'Opposite ABC Engineering College',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411007',
      latitude: 18.5314,
      longitude: 73.8446,
    },
    complaintCount: 17,
    averagePriorityScore: 92,
    highestPriority: 'CRITICAL',
    firstReportedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    latestReportedAt: new Date(Date.now() - 3600000).toISOString(),
    status: 'In Progress',
    summary: 'Massive craters and waterlogged potholes along 300m stretch outside ABC College leading to severe 2-wheeler skids and traffic jams during peak student hours.',
    complaintIds: [
      'JS-2026-001001',
      'JS-2026-001002',
      'JS-2026-001003',
      'JS-2026-001004',
      'JS-2026-001005',
    ],
  },
  {
    id: 'CLUSTER-PUNE-002',
    title: 'Central Market Dumpster Overflow & Biomedical Waste',
    category: 'Garbage & Sanitation',
    department: 'Sanitation Department',
    location: {
      address: 'Central Market Mandi Road, Lane 4',
      landmark: 'Behind Vegetable Wholesale Complex',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411002',
      latitude: 18.5186,
      longitude: 73.8553,
    },
    complaintCount: 14,
    averagePriorityScore: 84,
    highestPriority: 'HIGH',
    firstReportedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    latestReportedAt: new Date(Date.now() - 7200000).toISOString(),
    status: 'Assigned',
    summary: 'Uncollected organic and market waste rotting for 5+ days causing noxious stench, stray cattle menace, and severe risk of mosquito-borne disease.',
    complaintIds: ['JS-2026-001006', 'JS-2026-001007', 'JS-2026-001008'],
  },
  {
    id: 'CLUSTER-PUNE-003',
    title: 'Railway Station Underpass Complete Streetlight Blackout',
    category: 'Streetlights',
    department: 'Electrical & Lighting Department',
    location: {
      address: 'Station Road Subway & Pedestrian Underpass',
      landmark: 'Pune Junction South Exit',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411001',
      latitude: 18.5284,
      longitude: 73.8744,
    },
    complaintCount: 9,
    averagePriorityScore: 88,
    highestPriority: 'HIGH',
    firstReportedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    latestReportedAt: new Date(Date.now() - 14400000).toISOString(),
    status: 'In Progress',
    summary: 'All 14 sodium/LED lamps dysfunctional in the station subway, leading to safety hazards for late-night female commuters and elderly passengers.',
    complaintIds: ['JS-2026-001009', 'JS-2026-001010'],
  },
  {
    id: 'CLUSTER-PUNE-004',
    title: 'Baner Main Line Contaminated Muddy Water Supply',
    category: 'Water Supply',
    department: 'Water Supply & Sewerage Board',
    location: {
      address: 'Baner High Street Crossroad, Ward 8',
      landmark: 'Near Balewadi Phata',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411045',
      latitude: 18.5642,
      longitude: 73.7769,
    },
    complaintCount: 11,
    averagePriorityScore: 91,
    highestPriority: 'CRITICAL',
    firstReportedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    latestReportedAt: new Date(Date.now() - 1800000).toISOString(),
    status: 'Assigned',
    summary: 'Direct sewage backflow mixing into drinking water pipelines; residents reported foul odor and waterborne stomach infections in societies.',
    complaintIds: ['JS-2026-001011', 'JS-2026-001012'],
  },
  {
    id: 'CLUSTER-PUNE-005',
    title: 'Kothrud DP Road Open Stormwater Drain Collapse',
    category: 'Drainage',
    department: 'Stormwater & Drainage Department',
    location: {
      address: 'DP Road, Opp Yashwantrao Natyagruha',
      landmark: 'Near Ashish Garden',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411038',
      latitude: 18.5074,
      longitude: 73.8077,
    },
    complaintCount: 7,
    averagePriorityScore: 78,
    highestPriority: 'HIGH',
    firstReportedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    latestReportedAt: new Date(Date.now() - 28800000).toISOString(),
    status: 'Resolved',
    summary: 'Concrete chamber cover broken on footpath exposing a 6-foot deep drain, repaired with reinforced iron grating.',
    complaintIds: ['JS-2026-001013'],
  },
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'JS-2026-001001',
    citizenId: 'user-citizen-1',
    citizenName: 'Aarav Sharma',
    citizenPhone: '+91 98201 44521',
    grievance: 'There is a huge pothole near ABC College and two people have already fallen from their bikes this morning.',
    summary: 'Deep, hazardous road pothole outside ABC College causing 2-wheeler accidents.',
    category: 'Roads & Infrastructure',
    department: 'PWD / Municipal Roads',
    priority: 'CRITICAL',
    priorityScore: 94,
    priorityReason: 'Immediate public safety risk with documented physical injuries near a high-footfall educational institution.',
    language: 'English',
    languageCode: 'en',
    location: {
      address: 'ABC College Road, Gate 2, Ganeshkhind',
      landmark: 'In front of ABC College canteen gate',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411007',
      latitude: 18.5314,
      longitude: 73.8446,
    },
    photoUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=600&q=80',
    clusterId: 'CLUSTER-PUNE-001',
    clusterTitle: 'ABC College Road Severe Potholes & Road Cratering',
    isDuplicate: true,
    duplicateOfId: 'JS-2026-001002',
    similarityScore: 94,
    status: 'In Progress',
    assignedOfficer: 'Shri Rajesh Kulkarni (EE PWD)',
    internalNotes: [
      'Rapid road repair gang dispatched with cold mix asphalt.',
      'Barricades placed around 2m crater temporarily.',
    ],
    statusHistory: [
      {
        status: 'Submitted',
        timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
        updatedBy: 'Citizen (Aarav Sharma)',
      },
      {
        status: 'AI Analyzed',
        timestamp: new Date(Date.now() - 3600000 * 5 + 4000).toISOString(),
        updatedBy: 'JanSetu AI Engine',
        note: 'High severity classified due to active accidents mentioned.',
      },
      {
        status: 'Assigned',
        timestamp: new Date(Date.now() - 3600000 * 4).toISOString(),
        updatedBy: 'Central Municipal Dispatcher',
        note: 'Routed to PWD Zone 2.',
      },
      {
        status: 'In Progress',
        timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
        updatedBy: 'Shri Rajesh Kulkarni',
        note: 'Repair team on site with asphalt machinery.',
      },
    ],
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'JS-2026-001002',
    citizenId: 'user-citizen-2',
    citizenName: 'Pooja Deshmukh',
    citizenPhone: '+91 97654 32190',
    grievance: 'एबीसी कॉलेजच्या बाहेर रस्त्यावर मोठा खड्डा पडला आहे, गाड्या आदळत आहेत.',
    summary: 'Large crater on the road outside ABC College causing vehicle damage and traffic slowdown.',
    category: 'Roads & Infrastructure',
    department: 'PWD / Municipal Roads',
    priority: 'HIGH',
    priorityScore: 89,
    priorityReason: 'Repeated vehicle collisions and traffic congestion along primary college thoroughfare.',
    language: 'Marathi',
    languageCode: 'mr',
    location: {
      address: 'ABC College Main Road, Near Bus Stop',
      landmark: 'Near ABC College Bus Stand',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411007',
      latitude: 18.5312,
      longitude: 73.8448,
    },
    clusterId: 'CLUSTER-PUNE-001',
    clusterTitle: 'ABC College Road Severe Potholes & Road Cratering',
    isDuplicate: true,
    similarityScore: 91,
    status: 'In Progress',
    assignedOfficer: 'Shri Rajesh Kulkarni (EE PWD)',
    statusHistory: [
      {
        status: 'Submitted',
        timestamp: new Date(Date.now() - 3600000 * 12).toISOString(),
        updatedBy: 'Citizen (Pooja Deshmukh)',
      },
      {
        status: 'AI Analyzed',
        timestamp: new Date(Date.now() - 3600000 * 12 + 3000).toISOString(),
        updatedBy: 'JanSetu AI Engine',
      },
      {
        status: 'In Progress',
        timestamp: new Date(Date.now() - 3600000 * 6).toISOString(),
        updatedBy: 'Shri Rajesh Kulkarni',
      },
    ],
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    id: 'JS-2026-001006',
    citizenId: 'user-citizen-3',
    citizenName: 'Vikram Joshi',
    citizenPhone: '+91 99887 76655',
    grievance: 'आमच्या भागात पाच दिवसांपासून कचरा उचललेला नाही. सेंट्रल मार्केट जवळ दुर्गंधी पसरली आहे.',
    summary: 'Garbage dump not cleared for 5 consecutive days near Central Market generating foul odor.',
    category: 'Garbage & Sanitation',
    department: 'Sanitation Department',
    priority: 'HIGH',
    priorityScore: 86,
    priorityReason: 'Prolonged accumulation of decomposing organic waste posing serious public health hazard.',
    language: 'Marathi',
    languageCode: 'mr',
    location: {
      address: 'Lane 4, Central Market Mandi',
      landmark: 'Near Wholesale Tomato Stalls',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411002',
      latitude: 18.5186,
      longitude: 73.8553,
    },
    photoUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=600&q=80',
    clusterId: 'CLUSTER-PUNE-002',
    clusterTitle: 'Central Market Dumpster Overflow & Biomedical Waste',
    isDuplicate: true,
    similarityScore: 88,
    status: 'Assigned',
    assignedOfficer: 'Smt. Anita Salve (Sanitary Inspector)',
    statusHistory: [
      {
        status: 'Submitted',
        timestamp: new Date(Date.now() - 3600000 * 18).toISOString(),
        updatedBy: 'Citizen (Vikram Joshi)',
      },
      {
        status: 'AI Analyzed',
        timestamp: new Date(Date.now() - 3600000 * 18 + 4000).toISOString(),
        updatedBy: 'JanSetu AI Engine',
      },
      {
        status: 'Assigned',
        timestamp: new Date(Date.now() - 3600000 * 10).toISOString(),
        updatedBy: 'Sanitation Supervisor',
      },
    ],
    createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 10).toISOString(),
  },
  {
    id: 'JS-2026-001009',
    citizenId: 'user-citizen-4',
    citizenName: 'Sneha Roy',
    citizenPhone: '+91 98112 23344',
    grievance: 'The entire railway station underpass is completely dark because all streetlights have failed. It is unsafe for women walking home at night.',
    summary: 'Complete blackout in railway station pedestrian underpass due to faulty streetlights.',
    category: 'Streetlights',
    department: 'Electrical & Lighting Department',
    priority: 'HIGH',
    priorityScore: 88,
    priorityReason: 'Severe women commuter security risk and trip hazards in crowded transit corridor.',
    language: 'English',
    languageCode: 'en',
    location: {
      address: 'Pune Railway Station South Underpass',
      landmark: 'Platform 1 to South Booking Office walkway',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411001',
      latitude: 18.5284,
      longitude: 73.8744,
    },
    clusterId: 'CLUSTER-PUNE-003',
    clusterTitle: 'Railway Station Underpass Complete Streetlight Blackout',
    isDuplicate: false,
    status: 'In Progress',
    assignedOfficer: 'Er. Mahesh Jadhav (EE Electrical)',
    statusHistory: [
      {
        status: 'Submitted',
        timestamp: new Date(Date.now() - 3600000 * 24).toISOString(),
        updatedBy: 'Citizen (Sneha Roy)',
      },
      {
        status: 'AI Analyzed',
        timestamp: new Date(Date.now() - 3600000 * 24 + 2000).toISOString(),
        updatedBy: 'JanSetu AI Engine',
      },
      {
        status: 'In Progress',
        timestamp: new Date(Date.now() - 3600000 * 8).toISOString(),
        updatedBy: 'Er. Mahesh Jadhav',
        note: 'Replacing blown fuse boxes and installing new high-output LED fixtures.',
      },
    ],
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'JS-2026-001011',
    citizenId: 'user-citizen-5',
    citizenName: 'Anand Nair',
    citizenPhone: '+91 97401 55667',
    grievance: 'हमारे इलाके में नलों से बहुत गंदा और बदबूदार पानी आ रहा है। कई बच्चे बीमार पड़ चुके हैं।',
    summary: 'Contaminated tap water with foul odor causing gastrointestinal illness among local children.',
    category: 'Water Supply',
    department: 'Water Supply & Sewerage Board',
    priority: 'CRITICAL',
    priorityScore: 96,
    priorityReason: 'Direct waterborne contamination resulting in reported illness among vulnerable minors.',
    language: 'Hindi',
    languageCode: 'hi',
    location: {
      address: 'Baner Main Road, Society Cluster 4',
      landmark: 'Near Balewadi Phata High Street',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411045',
      latitude: 18.5642,
      longitude: 73.7769,
    },
    clusterId: 'CLUSTER-PUNE-004',
    clusterTitle: 'Baner Main Line Contaminated Muddy Water Supply',
    isDuplicate: true,
    similarityScore: 95,
    status: 'Assigned',
    assignedOfficer: 'Shri Vinod Patil (Water Quality Chief)',
    statusHistory: [
      {
        status: 'Submitted',
        timestamp: new Date(Date.now() - 3600000 * 14).toISOString(),
        updatedBy: 'Citizen (Anand Nair)',
      },
      {
        status: 'AI Analyzed',
        timestamp: new Date(Date.now() - 3600000 * 14 + 3000).toISOString(),
        updatedBy: 'JanSetu AI Engine',
      },
      {
        status: 'Assigned',
        timestamp: new Date(Date.now() - 3600000 * 11).toISOString(),
        updatedBy: 'Water Board Rapid Action Cell',
      },
    ],
    createdAt: new Date(Date.now() - 3600000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 11).toISOString(),
  },
  {
    id: 'JS-2026-001013',
    citizenId: 'user-citizen-6',
    citizenName: 'Meenakshi Iyer',
    grievance: 'Footpath open drainage slab is broken in Kothrud near Natyagruha, pedestrian can fall straight in.',
    summary: 'Broken slab on stormwater drain along active pedestrian footpath.',
    category: 'Drainage',
    department: 'Stormwater & Drainage Department',
    priority: 'HIGH',
    priorityScore: 82,
    priorityReason: 'Fall hazard on busy pedestrian sidewalk near public auditorium.',
    language: 'English',
    languageCode: 'en',
    location: {
      address: 'DP Road, Near Yashwantrao Natyagruha',
      landmark: 'Opposite Kothrud Bus Depot',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411038',
      latitude: 18.5074,
      longitude: 73.8077,
    },
    clusterId: 'CLUSTER-PUNE-005',
    clusterTitle: 'Kothrud DP Road Open Stormwater Drain Collapse',
    isDuplicate: false,
    status: 'Resolved',
    assignedOfficer: 'Shri Santosh Gaikwad (Ward Officer)',
    statusHistory: [
      {
        status: 'Submitted',
        timestamp: new Date(Date.now() - 86400000 * 4).toISOString(),
        updatedBy: 'Citizen (Meenakshi Iyer)',
      },
      {
        status: 'AI Analyzed',
        timestamp: new Date(Date.now() - 86400000 * 4 + 2000).toISOString(),
        updatedBy: 'JanSetu AI Engine',
      },
      {
        status: 'Assigned',
        timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
        updatedBy: 'Drainage Division',
      },
      {
        status: 'In Progress',
        timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
        updatedBy: 'Ward 12 Maintenance Team',
      },
      {
        status: 'Resolved',
        timestamp: new Date(Date.now() - 86400000 * 1).toISOString(),
        updatedBy: 'Shri Santosh Gaikwad',
        note: 'Heavy-duty steel-reinforced cover installed and cemented.',
      },
    ],
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'JS-2026-001014',
    citizenId: 'user-citizen-7',
    citizenName: 'Gurpreet Singh',
    grievance: 'Traffic signal at Swargate junction is blinking yellow for 2 days causing huge 1-hour bottlenecks.',
    summary: 'Traffic signal failure at Swargate junction creating severe peak hour congestion.',
    category: 'Traffic',
    department: 'Traffic Police & Transport',
    priority: 'MEDIUM',
    priorityScore: 72,
    priorityReason: 'Major traffic slowdown at key arterial transit hub.',
    language: 'English',
    languageCode: 'en',
    location: {
      address: 'Swargate Flyover Junction',
      landmark: 'Near ST Stand Entrance',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411042',
      latitude: 18.5018,
      longitude: 73.8584,
    },
    status: 'In Progress',
    assignedOfficer: 'Inspector V. Shinde (Traffic Branch)',
    statusHistory: [
      {
        status: 'Submitted',
        timestamp: new Date(Date.now() - 3600000 * 16).toISOString(),
        updatedBy: 'Citizen (Gurpreet Singh)',
      },
      {
        status: 'In Progress',
        timestamp: new Date(Date.now() - 3600000 * 4).toISOString(),
        updatedBy: 'Traffic Signal Unit',
      },
    ],
    createdAt: new Date(Date.now() - 3600000 * 16).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'JS-2026-001015',
    citizenId: 'user-citizen-8',
    citizenName: 'Sunita Patil',
    grievance: 'Stray dog pack has become aggressive inside Kamala Nehru Park children play zone.',
    summary: 'Aggressive stray dogs inside municipal park children play area.',
    category: 'Parks & Public Spaces',
    department: 'Parks & Horticulture Department',
    priority: 'MEDIUM',
    priorityScore: 68,
    priorityReason: 'Safety concern for young children visiting public playground.',
    language: 'English',
    languageCode: 'en',
    location: {
      address: 'Kamala Nehru Park, Erandwane',
      landmark: 'Near Children Carousel',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411004',
      latitude: 18.5147,
      longitude: 73.8341,
    },
    status: 'Submitted',
    statusHistory: [
      {
        status: 'Submitted',
        timestamp: new Date(Date.now() - 3600000 * 6).toISOString(),
        updatedBy: 'Citizen (Sunita Patil)',
      },
    ],
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    id: 'JS-2026-001016',
    citizenId: 'user-citizen-9',
    citizenName: 'Manoj Kumar',
    grievance: '11KV electricity transformer sparking continuously with burning smell near residential school.',
    summary: 'High voltage transformer sparking and emitting smoke adjacent to school.',
    category: 'Electricity',
    department: 'Power Distribution Corporation',
    priority: 'CRITICAL',
    priorityScore: 98,
    priorityReason: 'Immediate electrocution and fire hazard in close proximity to children school.',
    language: 'English',
    languageCode: 'en',
    location: {
      address: 'Karve Road, Lane 7',
      landmark: 'Next to St. Jude Public School Gate',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411038',
      latitude: 18.5061,
      longitude: 73.8224,
    },
    status: 'In Progress',
    assignedOfficer: 'Er. R. K. Verma (MSEDCL Safety Squad)',
    statusHistory: [
      {
        status: 'Submitted',
        timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
        updatedBy: 'Citizen (Manoj Kumar)',
      },
      {
        status: 'In Progress',
        timestamp: new Date(Date.now() - 3600000 * 1).toISOString(),
        updatedBy: 'MSEDCL Emergency Response',
      },
    ],
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
];

export const INITIAL_HOTSPOTS: Hotspot[] = [
  {
    id: 'HOTSPOT-01',
    name: 'ABC College Road',
    location: {
      address: 'ABC College Road, Sector 3',
      landmark: 'Near University Circle',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411007',
      latitude: 18.5314,
      longitude: 73.8446,
    },
    complaintCount: 17,
    criticalCount: 7,
    highCount: 8,
    mainCategory: 'Roads & Infrastructure',
    clusterId: 'CLUSTER-PUNE-001',
  },
  {
    id: 'HOTSPOT-02',
    name: 'Central Market',
    location: {
      address: 'Central Market Mandi',
      landmark: 'Wholesale Yard',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411002',
      latitude: 18.5186,
      longitude: 73.8553,
    },
    complaintCount: 14,
    criticalCount: 2,
    highCount: 10,
    mainCategory: 'Garbage & Sanitation',
    clusterId: 'CLUSTER-PUNE-002',
  },
  {
    id: 'HOTSPOT-03',
    name: 'Railway Station Subway',
    location: {
      address: 'Station Road Subway',
      landmark: 'Pune Junction South Area',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411001',
      latitude: 18.5284,
      longitude: 73.8744,
    },
    complaintCount: 9,
    criticalCount: 1,
    highCount: 7,
    mainCategory: 'Streetlights',
    clusterId: 'CLUSTER-PUNE-003',
  },
  {
    id: 'HOTSPOT-04',
    name: 'Baner Main Road',
    location: {
      address: 'Baner High Street Cross',
      landmark: 'Balewadi Phata',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411045',
      latitude: 18.5642,
      longitude: 73.7769,
    },
    complaintCount: 11,
    criticalCount: 6,
    highCount: 4,
    mainCategory: 'Water Supply',
    clusterId: 'CLUSTER-PUNE-004',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-001',
    userId: 'user-citizen-1',
    complaintId: 'JS-2026-001001',
    title: 'Work In Progress on Pothole Report',
    message: 'PWD Ward Engineer Shri Rajesh Kulkarni has initiated on-site road filling on ABC College Road.',
    type: 'info',
    read: false,
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'NOTIF-002',
    userId: 'user-citizen-1',
    complaintId: 'JS-2026-001001',
    title: 'Grievance AI Analyzed',
    message: 'Your complaint was marked CRITICAL (Score 94/100) due to reported accident hazards and routed to PWD.',
    type: 'warning',
    read: true,
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'NOTIF-003',
    userId: 'user-citizen-6',
    complaintId: 'JS-2026-001013',
    title: 'Drainage Issue Resolved',
    message: 'Ward 12 team has replaced the damaged drain cover on Kothrud DP Road with reinforced iron slab.',
    type: 'success',
    read: false,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];
